# Project information
site_name: My new MkDocs site
# site_url: https://squidfunk.github.io/mkdocs-material/
site_author: Axel Bjelke
site_description: Description of my new site comes here...

# Repository
# repo_name: squidfunk/mkdocs-material
# repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
copyright: Copyright &copy; 2025 Axel Bjelke - This work is licensed under CC BY-NC-SA 4.0

# Configuration
theme:
  # Setup and theme structure: https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure
  name: material
  # custom_dir: material/overrides
  # Changing the logo and icons: https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
  #logo: assets/logo.png
  #favicon: assets/favicon.ico
  #icon:
  #  repo: fontawesome/brands/github
  #  logo: fontawesome/regular/folder-open
  # Changing the fonts: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Roboto
    code: Roboto Mono
  # Changing the language: https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/
  language: en
  # Changing the colors: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: teal
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # Setting up navigation: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.tabs # When tabs are enabled, top-level sections are rendered in a menu layer below the header for viewports above 1220px, but remain as-is on mobile.
    - navigation.tabs.sticky # When sticky tabs are enabled, navigation tabs will lock below the header and always remain visible when scrolling down.
    - navigation.sections # When sections are enabled, top-level sections are rendered as groups in the sidebar for viewports above 1220px, but remain as-is on mobile.
    - toc.follow # When anchor following for the table of contents is enabled, the sidebar is automatically scrolled so that the active anchor is always visible.
  # insiders only
    # - navigation.path # breadcrumbs at the top of each page
    # - search.suggest

# Plugins
plugins:
  # Built-in plugins: https://squidfunk.github.io/mkdocs-material/plugins/
  # - blog
  # - privacy
  - search
  # - tags
  # External plugins:
  # - glightbox: # Documentation: https://squidfunk.github.io/mkdocs-material/reference/images/#lightbox
  # - material-plausible # Documentation: https://github.com/notpushkin/material-plausible-plugin
  # - minify # Documentation: https://github.com/byrnereese/mkdocs-minify-plugin
  #      minify_html: true

# Hooks

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated

# Extensions
markdown_extensions:
  - admonition # enables coloured blocks mid article
  - attr_list # improves image handling
  - md_in_html # grids (insiders)
  - pymdownx.details # enables collapsible admonitions
  - footnotes
  - toc:
      permalink: true
      toc_depth: 4
  - abbr # enables glossary
  - pymdownx.snippets: # enables glossary
      auto_append:
        - overrides/glossary.md
  - pymdownx.keys # display keyboard commands nicely ++ctrl+alt+del++
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Main topic:
    - New entry: testfolder/index.md
    - Test:
      - testfolder/index.md
  - Topic 2:
    - Entry 2: testfolder/index.md      